syntax_items = [
	["text", "Plain Text"],
	["Cucumber", "Gherkin"],
	["abap", "ABAP"],
	["ada", "Ada"],
	["ahk", "autohotkey"],
	["antlr", "ANTLR"],
	["antlr-as", "ANTLR With ActionScript Target"],
	["antlr-cpp", "ANTLR With CPP Target"],
	["antlr-csharp", "ANTLR With C# Target"],
	["antlr-java", "ANTLR With Java Target"],
	["antlr-objc", "ANTLR With ObjectiveC Target"],
	["antlr-perl", "ANTLR With Perl Target"],
	["antlr-python", "ANTLR With Python Target"],
	["antlr-ruby", "ANTLR With Ruby Target"],
	["apacheconf", "ApacheConf"],
	["applescript", "AppleScript"],
	["as", "ActionScript"],
	["as3", "ActionScript 3"],
	["aspx-cs", "aspx-cs"],
	["aspx-vb", "aspx-vb"],
	["asy", "Asymptote"],
	["basemake", "Makefile"],
	["bash", "Bash"],
	["bat", "Batchfile"],
	["bbcode", "BBCode"],
	["befunge", "Befunge"],
	["blitzmax", "BlitzMax"],
	["boo", "Boo"],
	["c", "C"],
	["c-objdump", "c-objdump"],
	["cfm", "Coldfusion HTML"],
	["cfs", "cfstatement"],
	["cheetah", "Cheetah"],
	["clojure", "Clojure"],
	["cmake", "CMake"],
	["coffee-script", "CoffeeScript"],
	["common-lisp", "Common Lisp"],
	["console", "Bash Session"],
	["control", "Debian Control file"],
	["cpp", "C++"],
	["cpp-objdump", "cpp-objdump"],
	["csharp", "C#"],
	["css", "CSS"],
	["css+django", "CSS+Django/Jinja"],
	["css+erb", "CSS+Ruby"],
	["css+genshitext", "CSS+Genshi Text"],
	["css+mako", "CSS+Mako"],
	["css+myghty", "CSS+Myghty"],
	["css+php", "CSS+PHP"],
	["css+smarty", "CSS+Smarty"],
	["cython", "Cython"],
	["d", "D"],
	["d-objdump", "d-objdump"],
	["delphi", "Delphi"],
	["diff", "Diff"],
	["django", "Django/Jinja"],
	["dpatch", "Darcs Patch"],
	["duel", "Duel"],
	["dylan", "Dylan"],
	["erb", "ERB"],
	["erl", "Erlang erl session"],
	["erlang", "Erlang"],
	["evoque", "Evoque"],
	["factor", "Factor"],
	["felix", "Felix"],
	["fortran", "Fortran"],
	["gas", "GAS"],
	["genshi", "Genshi"],
	["genshitext", "Genshi Text"],
	["glsl", "GLSL"],
	["gnuplot", "Gnuplot"],
	["go", "Go"],
	["gooddata-cl", "GoodData-CL"],
	["groff", "Groff"],
	["haml", "Haml"],
	["haskell", "Haskell"],
	["html", "HTML"],
	["html+cheetah", "HTML+Cheetah"],
	["html+django", "HTML+Django/Jinja"],
	["html+evoque", "HTML+Evoque"],
	["html+genshi", "HTML+Genshi"],
	["html+mako", "HTML+Mako"],
	["html+myghty", "HTML+Myghty"],
	["html+php", "HTML+PHP"],
	["html+smarty", "HTML+Smarty"],
	["html+velocity", "HTML+Velocity"],
	["hx", "haXe"],
	["hybris", "Hybris"],
	["ini", "INI"],
	["io", "Io"],
	["ioke", "Ioke"],
	["irc", "IRC logs"],
	["jade", "Jade"],
	["java", "Java"],
	["js", "JavaScript"],
	["js+cheetah", "JavaScript+Cheetah"],
	["js+django", "JavaScript+Django/Jinja"],
	["js+erb", "JavaScript+Ruby"],
	["js+genshitext", "JavaScript+Genshi Text"],
	["js+mako", "JavaScript+Mako"],
	["js+myghty", "JavaScript+Myghty"],
	["js+php", "JavaScript+PHP"],
	["js+smarty", "JavaScript+Smarty"],
	["jsp", "Java Server Page"],
	["lhs", "Literate Haskell"],
	["lighty", "Lighttpd configuration file"],
	["llvm", "LLVM"],
	["logtalk", "Logtalk"],
	["lua", "Lua"],
	["make", "Makefile"],
	["mako", "Mako"],
	["maql", "MAQL"],
	["mason", "Mason"],
	["matlab", "Matlab"],
	["matlabsession", "Matlab session"],
	["minid", "MiniD"],
	["modelica", "Modelica"],
	["modula2", "Modula-2"],
	["moocode", "MOOCode"],
	["mupad", "MuPAD"],
	["mxml", "MXML"],
	["myghty", "Myghty"],
	["mysql", "MySQL"],
	["nasm", "NASM"],
	["newspeak", "Newspeak"],
	["nginx", "Nginx configuration file"],
	["numpy", "NumPy"],
	["objdump", "objdump"],
	["objective-c", "Objective-C"],
	["objective-j", "Objective-J"],
	["ocaml", "OCaml"],
	["ooc", "Ooc"],
	["perl", "Perl"],
	["php", "PHP"],
	["postscript", "PostScript"],
	["pot", "Gettext Catalog"],
	["pov", "POVRay"],
	["prolog", "Prolog"],
	["properties", "Properties"],
	["protobuf", "Protocol Buffer"],
	["py3tb", "Python 3.0 Traceback"],
	["pycon", "Python console session"],
	["pytb", "Python Traceback"],
	["python", "Python"],
	["python3", "Python 3"],
	["ragel", "Ragel"],
	["ragel-c", "Ragel in C Host"],
	["ragel-cpp", "Ragel in CPP Host"],
	["ragel-d", "Ragel in D Host"],
	["ragel-em", "Embedded Ragel"],
	["ragel-java", "Ragel in Java Host"],
	["ragel-objc", "Ragel in Objective C Host"],
	["ragel-ruby", "Ragel in Ruby Host"],
	["raw", "Raw token data"],
	["rb", "Ruby"],
	["rbcon", "Ruby irb session"],
	["rconsole", "RConsole"],
	["rebol", "REBOL"],
	["redcode", "Redcode"],
	["rhtml", "RHTML"],
	["rst", "reStructuredText"],
	["sass", "Sass"],
	["scala", "Scala"],
	["scaml", "Scaml"],
	["scheme", "Scheme"],
	["scss", "SCSS"],
	["smalltalk", "Smalltalk"],
	["smarty", "Smarty"],
	["sourceslist", "Debian Sourcelist"],
	["splus", "S"],
	["sql", "SQL"],
	["sqlite3", "sqlite3con"],
	["squidconf", "SquidConf"],
	["ssp", "Scalate Server Page"],
	["tcl", "Tcl"],
	["tcsh", "Tcsh"],
	["tex", "TeX"],
	["text", "Text only"],
	["trac-wiki", "MoinMoin/Trac Wiki markup"],
	["v", "verilog"],
	["vala", "Vala"],
	["vb.net", "VB.net"],
	["velocity", "Velocity"],
	["vim", "VimL"],
	["xml", "XML"],
	["xml+cheetah", "XML+Cheetah"],
	["xml+django", "XML+Django/Jinja"],
	["xml+erb", "XML+Ruby"],
	["xml+evoque", "XML+Evoque"],
	["xml+mako", "XML+Mako"],
	["xml+myghty", "XML+Myghty"],
	["xml+php", "XML+PHP"],
	["xml+smarty", "XML+Smarty"],
	["xml+velocity", "XML+Velocity"],
	["xquery", "XQuery"],
	["xslt", "XSLT"],
	["yaml", "YAML"]]